// <auto-generated />
using AB3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AB3.Migrations
{
    [DbContext(typeof(AB3Context))]
    partial class AB3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ABPort.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<int?>("ProjectID");

                    b.HasKey("Id");

                    b.HasIndex("ProjectID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ABPort.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageName");

                    b.Property<bool>("IsCover");

                    b.Property<int?>("ProjectID");

                    b.Property<string>("Src");

                    b.HasKey("Id");

                    b.HasIndex("ProjectID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ABPort.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("UnitsInStock");

                    b.Property<int>("ViewCount");

                    b.Property<string>("Year");

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ABPort.Models.Category", b =>
                {
                    b.HasOne("ABPort.Models.Project")
                        .WithMany("Categories")
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("ABPort.Models.Image", b =>
                {
                    b.HasOne("ABPort.Models.Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectID");
                });
#pragma warning restore 612, 618
        }
    }
}
